---
- name: "Virtualbox.yml"
  hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: Ensure dependencies are installed
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bzip2
      - dkms
      - kernel-devel
      - kernel-headers

  - name: Mount VBoxGuestAdditions.iso
    mount:
      path: /mnt
      src: /home/packer/VBoxGuestAdditions.iso
      fstype: iso9660
      opts: ro,loop
      state: mounted

  - name: Install VBoxGuestAdditions.iso
    shell: sh /mnt/VBoxLinuxAdditions.run

  - name: Umount VBoxGuestAdditions.iso
    mount:
      path: /mnt
      state: unmounted

  - name: Delete VBoxGuestAdditions.iso
    file:
      path: /home/packer/VBoxGuestAdditions.iso
      state: absent